version: 2.1
jobs:
  build-and-test:
    docker: # run the steps with Docker
      - image: cimg/node:20.17
    steps:
      - checkout
      - run:
          name: install-node-packages
          command: "npm install"
      - run:
          name: eslint
          command: "npx eslint --ext .ts,.html --max-warnings 0 ./"
      - run:
          name: run-angular-lib-tests
          command: "npm run test -- --browsers=ChromeHeadless --watch=false ngx-ellipsis"
workflows:
    build-and-test:
      jobs:
        - build-and-test
